#!/bin/bash
# File: scripts/n8n-render-config.sh
# Render n8n env/config artifacts from .env values.

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)
# shellcheck source=scripts/common.sh
. "${SCRIPT_DIR}/common.sh"

load_env

require_nonempty() {
    local key="$1"
    local value="${2:-}"
    if [ -z "$value" ]; then
        log_error "Missing required n8n setting: ${key}"
    fi
}

normalize_bool() {
    case "${1:-false}" in
        true|false) printf '%s' "$1" ;;
        *) log_error "Invalid boolean value: ${1:-}" ;;
    esac
}

RENDER_DIR="${REPO_ROOT}/services/n8n/rendered"
RENDERED_ENV_PATH="${N8N_RENDERED_ENV_PATH:-${RENDER_DIR}/n8n.env}"
if [[ "${RENDERED_ENV_PATH}" != /* ]]; then
    RENDERED_ENV_PATH="${REPO_ROOT}/${RENDERED_ENV_PATH}"
fi
STEPCA_RENDERED_CERT_PATH="${RENDER_DIR}/stepca-root-ca.crt"
INSTALL_RUNBOOK_PATH="${RENDER_DIR}/install-checklist.md"
KEYCLOAK_RUNBOOK_PATH="${RENDER_DIR}/keycloak-oidc-checklist.md"
OBS_RUNBOOK_PATH="${RENDER_DIR}/observability.md"

mkdir -p "${RENDER_DIR}"
mkdir -p "$(dirname "${RENDERED_ENV_PATH}")"

N8N_HOSTNAME_VALUE="${N8N_HOSTNAME:-n8n}"
DEV_DOMAIN_VALUE="${DEV_DOMAIN:-}"
require_nonempty "DEV_DOMAIN" "${DEV_DOMAIN_VALUE}"
N8N_PUBLIC_URL="https://${N8N_HOSTNAME_VALUE}.${DEV_DOMAIN_VALUE}"
N8N_PORT_VALUE="${N8N_PORT:-5678}"
[[ "${N8N_PORT_VALUE}" =~ ^[0-9]+$ ]] || log_error "N8N_PORT must be numeric. Got: ${N8N_PORT_VALUE}"
N8N_DB_NAME_VALUE="${N8N_DB_NAME:-n8n}"
N8N_DB_USER_VALUE="${N8N_DB_USER:-n8n}"
N8N_DB_PASSWORD_VALUE="${N8N_DB_PASSWORD:-}"
N8N_ENCRYPTION_KEY_VALUE="${N8N_ENCRYPTION_KEY:-}"
require_nonempty "N8N_DB_PASSWORD" "${N8N_DB_PASSWORD_VALUE}"
require_nonempty "N8N_ENCRYPTION_KEY" "${N8N_ENCRYPTION_KEY_VALUE}"
N8N_DB_SCHEMA_VALUE="${N8N_DB_SCHEMA:-public}"
N8N_DIAGNOSTICS_ENABLED_VALUE=$(normalize_bool "${N8N_DIAGNOSTICS_ENABLED:-false}")
N8N_PROXY_HOPS_VALUE="${N8N_PROXY_HOPS:-1}"
[[ "${N8N_PROXY_HOPS_VALUE}" =~ ^[0-9]+$ ]] || log_error "N8N_PROXY_HOPS must be numeric. Got: ${N8N_PROXY_HOPS_VALUE}"
N8N_SECURE_COOKIE_VALUE=$(normalize_bool "${N8N_SECURE_COOKIE:-true}")
N8N_ENDPOINT_HEALTH_VALUE="${N8N_ENDPOINT_HEALTH:-healthz}"

KEYCLOAK_ENABLED=$(normalize_bool "${N8N_KEYCLOAK_ENABLE:-false}")
OBS_ENABLED=$(normalize_bool "${N8N_OBSERVABILITY_ENABLE:-false}")
OBS_MODE="${N8N_OBSERVABILITY_MODE:-health}"
STEPCA_TRUST_ENABLED=$(normalize_bool "${N8N_STEPCA_TRUST_ENABLE:-false}")

N8N_METRICS_VALUE=false
case "${OBS_MODE}" in
    health) ;;
    metrics|full) N8N_METRICS_VALUE=true ;;
    custom) N8N_METRICS_VALUE=$(normalize_bool "${N8N_METRICS_CUSTOM_ENABLE:-false}") ;;
    *) log_error "Invalid N8N_OBSERVABILITY_MODE: ${OBS_MODE}" ;;
esac

NODE_EXTRA_CA_CERTS_VALUE=""
if [ "${STEPCA_TRUST_ENABLED}" = "true" ]; then
    STEPCA_TRUST_SOURCE_PATH="${N8N_STEPCA_TRUST_SOURCE_PATH:-shared/certs/local-ca/ca.crt}"
    case "${STEPCA_TRUST_SOURCE_PATH}" in
        /*) STEPCA_SOURCE_FILE="${STEPCA_TRUST_SOURCE_PATH}" ;;
        *) STEPCA_SOURCE_FILE="${REPO_ROOT}/${STEPCA_TRUST_SOURCE_PATH}" ;;
    esac
    [ -f "${STEPCA_SOURCE_FILE}" ] || log_error "N8N_STEPCA_TRUST_ENABLE=true but CA file not found: ${STEPCA_SOURCE_FILE}"
    cp "${STEPCA_SOURCE_FILE}" "${STEPCA_RENDERED_CERT_PATH}"
    NODE_EXTRA_CA_CERTS_VALUE="/home/node/.n8n/certs/stepca-root-ca.crt"
else
    : > "${STEPCA_RENDERED_CERT_PATH}"
fi

cat > "${RENDERED_ENV_PATH}" <<EOV
# Generated by scripts/n8n-render-config.sh. Do not edit manually.
N8N_RENDER_STATUS=ready
N8N_PORT=${N8N_PORT_VALUE}
N8N_HOST=${N8N_HOSTNAME_VALUE}.${DEV_DOMAIN_VALUE}
N8N_PROTOCOL=https
WEBHOOK_URL=${N8N_PUBLIC_URL}/
N8N_EDITOR_BASE_URL=${N8N_PUBLIC_URL}/
N8N_PROXY_HOPS=${N8N_PROXY_HOPS_VALUE}
N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE_VALUE}
DB_TYPE=postgresdb
DB_POSTGRESDB_HOST=n8n-db
DB_POSTGRESDB_PORT=5432
DB_POSTGRESDB_DATABASE=${N8N_DB_NAME_VALUE}
DB_POSTGRESDB_USER=${N8N_DB_USER_VALUE}
DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD_VALUE}
DB_POSTGRESDB_SCHEMA=${N8N_DB_SCHEMA_VALUE}
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY_VALUE}
N8N_DIAGNOSTICS_ENABLED=${N8N_DIAGNOSTICS_ENABLED_VALUE}
N8N_ENDPOINT_HEALTH=${N8N_ENDPOINT_HEALTH_VALUE}
N8N_METRICS=${N8N_METRICS_VALUE}
NODE_EXTRA_CA_CERTS=${NODE_EXTRA_CA_CERTS_VALUE}
EOV

cat > "${INSTALL_RUNBOOK_PATH}" <<EOI
# n8n installation checklist (generated)

- Public URL: ${N8N_PUBLIC_URL}
- Health endpoint: ${N8N_PUBLIC_URL}/${N8N_ENDPOINT_HEALTH_VALUE}
- Webhook base URL: ${N8N_PUBLIC_URL}/
- Suggested owner email: ${N8N_OWNER_BOOTSTRAP_EMAIL:-admin@${DEV_DOMAIN_VALUE}}
- Suggested owner password: [from .env N8N_OWNER_BOOTSTRAP_PASSWORD; not printed]

## Install flow
1. Run \`make n8n-up\`.
2. Open ${N8N_PUBLIC_URL}.
3. Complete the owner setup with the suggested email/password from \`.env\`.
4. Verify workflows use the public webhook URL (${N8N_PUBLIC_URL}/).
EOI

if [ "${KEYCLOAK_ENABLED}" = "true" ]; then
    cat > "${KEYCLOAK_RUNBOOK_PATH}" <<EOK
# n8n OIDC / Keycloak checklist (generated)

n8n supports OIDC SSO configuration in the admin UI. Availability may depend on your n8n edition/license.

- n8n URL: ${N8N_PUBLIC_URL}
- Discovery endpoint (Keycloak): ${N8N_KEYCLOAK_DISCOVERY_URL:-<set N8N_KEYCLOAK_DISCOVERY_URL>}
- Client ID: ${N8N_KEYCLOAK_CLIENT_ID:-<set N8N_KEYCLOAK_CLIENT_ID>}
- Client secret: [configured in .env; not printed]
- Expected redirect URI pattern (shown in n8n UI): ${N8N_PUBLIC_URL}/rest/sso/oidc/callback

## n8n admin setup
1. Open Settings -> SSO -> OIDC.
2. Copy the redirect URL shown by n8n and add it to the Keycloak client.
3. Configure discovery endpoint, client ID, and client secret.
4. Activate OIDC and test login before disabling local auth.
EOK
else
    rm -f "${KEYCLOAK_RUNBOOK_PATH}"
fi

if [ "${OBS_ENABLED}" = "true" ]; then
    cat > "${OBS_RUNBOOK_PATH}" <<EOO
# n8n observability notes (generated)

Mode: ${OBS_MODE}
n8n URL: ${N8N_PUBLIC_URL}

## Endpoints
- Health: ${N8N_PUBLIC_URL}/${N8N_ENDPOINT_HEALTH_VALUE}
- Readiness: ${N8N_PUBLIC_URL}/${N8N_ENDPOINT_HEALTH_VALUE}/readiness
- Metrics: ${N8N_PUBLIC_URL}/metrics (requires N8N_METRICS=true)

## Current rendered settings
- N8N_METRICS=${N8N_METRICS_VALUE}
- N8N_ENDPOINT_HEALTH=${N8N_ENDPOINT_HEALTH_VALUE}

## Notes
- Health is available on the main n8n server by default.
- Metrics is disabled by default upstream and enabled only when the observability mode renders it.
EOO
else
    rm -f "${OBS_RUNBOOK_PATH}"
fi

log_info "Rendered n8n env: ${RENDERED_ENV_PATH}"
log_info "Rendered install checklist: ${INSTALL_RUNBOOK_PATH}"
if [ -f "${KEYCLOAK_RUNBOOK_PATH}" ]; then
    log_info "Rendered Keycloak OIDC checklist: ${KEYCLOAK_RUNBOOK_PATH}"
fi
if [ -f "${OBS_RUNBOOK_PATH}" ]; then
    log_info "Rendered observability notes: ${OBS_RUNBOOK_PATH}"
fi
