#!/bin/bash
# File: scripts/wikijs-render-config.sh
# Render Wiki.js env/config artifacts from .env values.

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)
# shellcheck source=scripts/common.sh
. "${SCRIPT_DIR}/common.sh"

load_env

require_nonempty() {
    local key="$1"
    local value="${2:-}"
    if [ -z "$value" ]; then
        log_error "Missing required Wiki.js setting: ${key}"
    fi
}

normalize_bool() {
    case "${1:-false}" in
        true|false) printf '%s' "$1" ;;
        *) log_error "Invalid boolean value: ${1:-}" ;;
    esac
}

RENDER_DIR="${REPO_ROOT}/services/wikijs/rendered"
RENDERED_ENV_PATH="${WIKIJS_RENDERED_ENV_PATH:-${RENDER_DIR}/wikijs.env}"
if [[ "${RENDERED_ENV_PATH}" != /* ]]; then
    RENDERED_ENV_PATH="${REPO_ROOT}/${RENDERED_ENV_PATH}"
fi
STEPCA_RENDERED_CERT_PATH="${RENDER_DIR}/stepca-root-ca.crt"
INSTALL_RUNBOOK_PATH="${RENDER_DIR}/install-checklist.md"
KEYCLOAK_RUNBOOK_PATH="${RENDER_DIR}/keycloak-checklist.md"
OBS_RUNBOOK_PATH="${RENDER_DIR}/observability.md"

mkdir -p "${RENDER_DIR}"
mkdir -p "$(dirname "${RENDERED_ENV_PATH}")"

WIKIJS_HOSTNAME_VALUE="${WIKIJS_HOSTNAME:-wiki}"
DEV_DOMAIN_VALUE="${DEV_DOMAIN:-}"
require_nonempty "DEV_DOMAIN" "${DEV_DOMAIN_VALUE}"
WIKIJS_PORT_VALUE="${WIKIJS_PORT:-3000}"
if [[ ! "${WIKIJS_PORT_VALUE}" =~ ^[0-9]+$ ]]; then
    log_error "WIKIJS_PORT must be numeric. Got: ${WIKIJS_PORT_VALUE}"
fi
WIKIJS_DB_NAME_VALUE="${WIKIJS_DB_NAME:-wiki}"
WIKIJS_DB_USER_VALUE="${WIKIJS_DB_USER:-wikijs}"
WIKIJS_DB_PASSWORD_VALUE="${WIKIJS_DB_PASSWORD:-}"
require_nonempty "WIKIJS_DB_PASSWORD" "${WIKIJS_DB_PASSWORD_VALUE}"
WIKIJS_DB_SSL_VALUE=$(normalize_bool "${WIKIJS_DB_SSL:-false}")
WIKIJS_HA_ACTIVE_VALUE=$(normalize_bool "${WIKIJS_HA_ACTIVE:-false}")
WIKIJS_LOG_LEVEL_VALUE="${WIKIJS_LOG_LEVEL:-info}"
WIKIJS_PUBLIC_URL="https://${WIKIJS_HOSTNAME_VALUE}.${DEV_DOMAIN_VALUE}"
WIKIJS_ADMIN_BOOTSTRAP_EMAIL_VALUE="${WIKIJS_ADMIN_BOOTSTRAP_EMAIL:-admin@${DEV_DOMAIN_VALUE}}"
WIKIJS_ADMIN_BOOTSTRAP_PASSWORD_VALUE="${WIKIJS_ADMIN_BOOTSTRAP_PASSWORD:-}"

KEYCLOAK_ENABLED=$(normalize_bool "${WIKIJS_KEYCLOAK_ENABLE:-false}")
OBS_ENABLED=$(normalize_bool "${WIKIJS_OBSERVABILITY_ENABLE:-false}")
STEPCA_TRUST_ENABLED=$(normalize_bool "${WIKIJS_STEPCA_TRUST_ENABLE:-false}")
OBS_MODE="${WIKIJS_OBSERVABILITY_MODE:-telemetry}"

NODE_EXTRA_CA_CERTS_VALUE=""
if [ "${STEPCA_TRUST_ENABLED}" = "true" ]; then
    STEPCA_TRUST_SOURCE_PATH="${WIKIJS_STEPCA_TRUST_SOURCE_PATH:-shared/certs/local-ca/ca.crt}"
    case "${STEPCA_TRUST_SOURCE_PATH}" in
        /*) STEPCA_SOURCE_FILE="${STEPCA_TRUST_SOURCE_PATH}" ;;
        *) STEPCA_SOURCE_FILE="${REPO_ROOT}/${STEPCA_TRUST_SOURCE_PATH}" ;;
    esac
    if [ ! -f "${STEPCA_SOURCE_FILE}" ]; then
        log_error "WIKIJS_STEPCA_TRUST_ENABLE=true but CA file not found: ${STEPCA_SOURCE_FILE}"
    fi
    cp "${STEPCA_SOURCE_FILE}" "${STEPCA_RENDERED_CERT_PATH}"
    NODE_EXTRA_CA_CERTS_VALUE="/wiki/certs/stepca-root-ca.crt"
else
    : > "${STEPCA_RENDERED_CERT_PATH}"
fi

cat > "${RENDERED_ENV_PATH}" <<EOV
# Generated by scripts/wikijs-render-config.sh. Do not edit manually.
WIKIJS_RENDER_STATUS=ready
PORT=${WIKIJS_PORT_VALUE}
DB_TYPE=postgres
DB_HOST=wikijs-db
DB_PORT=5432
DB_USER=${WIKIJS_DB_USER_VALUE}
DB_PASS=${WIKIJS_DB_PASSWORD_VALUE}
DB_NAME=${WIKIJS_DB_NAME_VALUE}
DB_SSL=${WIKIJS_DB_SSL_VALUE}
HA_ACTIVE=${WIKIJS_HA_ACTIVE_VALUE}
LOG_LEVEL=${WIKIJS_LOG_LEVEL_VALUE}
NODE_EXTRA_CA_CERTS=${NODE_EXTRA_CA_CERTS_VALUE}
EOV

cat > "${INSTALL_RUNBOOK_PATH}" <<EOI
# Wiki.js installation checklist (generated)

- Public URL: ${WIKIJS_PUBLIC_URL}
- Database: PostgreSQL (\`wikijs-db\`) using database \`${WIKIJS_DB_NAME_VALUE}\` and user \`${WIKIJS_DB_USER_VALUE}\`
- Suggested first admin email: ${WIKIJS_ADMIN_BOOTSTRAP_EMAIL_VALUE}
- Suggested first admin password: [from .env WIKIJS_ADMIN_BOOTSTRAP_PASSWORD; not printed]

## Install flow
1. Run \`make wikijs-up\`.
2. Open ${WIKIJS_PUBLIC_URL}.
3. Complete the setup wizard and choose PostgreSQL.
4. Use the DB values rendered for the module (host \`wikijs-db\`, port \`5432\`).
5. Set the initial admin account (you can use the suggested email/password from \`.env\`).
EOI

if [ "${KEYCLOAK_ENABLED}" = "true" ]; then
    cat > "${KEYCLOAK_RUNBOOK_PATH}" <<EOK
# Wiki.js Keycloak checklist (generated)

- Wiki.js URL: ${WIKIJS_PUBLIC_URL}
- Provider: Keycloak (built-in Wiki.js auth module exists upstream)
- Keycloak issuer URL: ${WIKIJS_KEYCLOAK_ISSUER_URL:-<set WIKIJS_KEYCLOAK_ISSUER_URL>}
- Client ID: ${WIKIJS_KEYCLOAK_CLIENT_ID:-<set WIKIJS_KEYCLOAK_CLIENT_ID>}
- Client secret: [configured in .env; not printed]

## Expected endpoints (derive from issuer/realm)
- Authorization: <issuer>/protocol/openid-connect/auth
- Token: <issuer>/protocol/openid-connect/token
- UserInfo: <issuer>/protocol/openid-connect/userinfo
- Logout: <issuer>/protocol/openid-connect/logout

## Wiki.js admin setup
1. Open Admin -> Authentication.
2. Enable the Keycloak provider.
3. Fill host/realm/client fields and the OIDC endpoints above.
4. Use the callback URL shown by the Wiki.js UI (copy it into the Keycloak client redirect URIs).
5. Test login before disabling local auth.
EOK
else
    rm -f "${KEYCLOAK_RUNBOOK_PATH}"
fi

if [ "${OBS_ENABLED}" = "true" ]; then
    cat > "${OBS_RUNBOOK_PATH}" <<EOO
# Wiki.js observability notes (generated)

Mode: ${OBS_MODE}
Wiki.js URL: ${WIKIJS_PUBLIC_URL}

## Scope implemented in this repo
- Container logs via docker compose / Traefik access logs
- Optional telemetry guidance (configured in Wiki.js Admin -> Utilities -> Telemetry)
- Runtime HTTP health reachability validation can use the public Wiki.js route after startup

## Upstream note
- If upstream documentation provides a fuller installable observability path for the target version, enable it under explicit toggles in a follow-up change.
EOO
else
    rm -f "${OBS_RUNBOOK_PATH}"
fi

log_info "Rendered Wiki.js env: ${RENDERED_ENV_PATH}"
log_info "Rendered install checklist: ${INSTALL_RUNBOOK_PATH}"
if [ -f "${KEYCLOAK_RUNBOOK_PATH}" ]; then
    log_info "Rendered Keycloak checklist: ${KEYCLOAK_RUNBOOK_PATH}"
fi
if [ -f "${OBS_RUNBOOK_PATH}" ]; then
    log_info "Rendered observability notes: ${OBS_RUNBOOK_PATH}"
fi
